env:
  - CGO_ENABLED=0
  - PROJECT=github.com/cloudradar-monitoring/rport
builds:
  - id: rport
    main: ./cmd/rport
    binary: rport
    ldflags:
      - "-s -w  -X {{.Env.PROJECT}}/share.BuildVersion={{.Version}}"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - ppc64
      - ppc64le
      - mips
      - mipsle
      - mips64
      - mips64le
      - mips64p32
      - mips64p32le
      - ppc
      - s390
      - s390x
    goarm:
      - 6
      - 7
    gomips:
      - hardfloat
      - softfloat
    ignore:
      - goos: darwin
        goarch: 386
  - id: rportd
    main: ./cmd/rportd
    binary: rportd
    ldflags:
      - "-s -w  -X {{.Env.PROJECT}}/share.BuildVersion={{.Version}}"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - ppc64
      - ppc64le
      - mips
      - mipsle
      - mips64
      - mips64le
      - mips64p32
      - mips64p32le
      - ppc
      - s390
      - s390x
    goarm:
      - 6
      - 7
    gomips:
      - hardfloat
      - softfloat
    ignore:
      - goos: darwin
        goarch: 386
archives:
  - format_overrides:
      - goos: windows
        format: zip
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
release:
  github:
    owner: cloudradar-monitoring
    name: rport
  draft: true
