name: Deploy

on:
  push:
    branches:
      - master

jobs:
  server:
    name: Server
    runs-on: ubuntu-latest
    # TODO(m-terel): consider to run all ssh commands at once if current execution would be overhead
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        # set rport version to {date-time}-sha:{github-master-head-sha}
        run: go build -v -ldflags="-X 'github.com/cloudradar-monitoring/rport/share.BuildVersion=`date -u +%d-%m-%Y.%H:%M:%S`-sha:`git rev-parse HEAD`'"  -o ./ ./cmd/...

      - name: Copy a new version to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: "rportd,rport"
          target: ${{ secrets.DEPLOY_FOLDER }}
          overwrite: true

      - name: Replace bin and Restart rport server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          script: |
            sudo service rportd stop
            sudo cp /home/github/binaries/rportd /usr/local/bin
            sudo cp /home/github/binaries/rport /usr/local/bin
            sudo service rportd start
