name: Go
on: [push]
jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: go mod vendor
        run: go mod vendor

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          go_version: '1.17'
          golangci_lint_version: '1.43.0'
  test:
    name: Test Server/Client Nix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: go test -race -v ./...

  test-win:
    name: Test Client Windows
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: go test -race -v ./client/...
