name: Go
on: [push]
jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: go mod vendor
        run: go mod vendor

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.32
          args: -c .golangci.yml
  test:
    name: Test Server/Client Nix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: go test -race -v ./...

  test-win:
    name: Test Client Windows
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: InstallTaco
        shell: pwsh
        run: .github/scripts/install-taco.ps1
      - name: Test
        run: go test -race -v ./client/...
