name: Go
on: [push]
jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: rm vendor
        run: rm -rf vendor

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: v1.43.0
          args: -c .golangci.yml
  test:
    name: Test Server/Client Nix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: go test -race -v ./...

  test-win:
    name: Test Client Windows
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: go test -race -v ./client/...
